<html>
    <head>
    </head>
    <body>


		<input name="DistanceAvantPlan" id="distanceAvantPlan" size="4" value="10.0" />

    	<div id="PhotoView">
            <canvas id="PhotoCanvas"></canvas>
        </div>

        <div id="FlouDeMAPView">
            <canvas id="FlouDeMAPCanvas"></canvas>
        </div>
        
        <script src="/js/libs.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>

